"""
Parses a reviewer-filled offline Excel workbook and returns structured response data.

The expected format is the file generated by excel_offline_exporter.py:
  Sheet: 'ReviewBot Response'
  Col A: item_code  (locked)
  Col B: area       (locked)
  Col C: team       (locked)
  Col D: question   (locked)
  Col E: expected_evidence (locked)
  Col F: guidance   (locked)
  Col G: Response   ← editable (Yes / No / Partial / N/A)
  Col H: Comments   ← editable
  Col I: Evidence Links ← editable (comma-separated)
"""
from typing import List, Dict, Any

import openpyxl

_RAG_MAP = {
    "yes": "green",
    "no": "red",
    "partial": "amber",
    "n/a": "na",
    "na": "na",
}

_SHEET_NAME = "ReviewBot Response"
_DATA_START_ROW = 3  # Row 1 = info bar, Row 2 = header, Row 3+ = data


def parse_response_excel(
    file_bytes: bytes,
    checklist_items: list,
) -> List[Dict[str, Any]]:
    """
    Parse a reviewer-completed offline Excel and return response records.

    Args:
        file_bytes: Raw bytes of the uploaded .xlsx file.
        checklist_items: List of ChecklistItem ORM objects from the review's checklist.
                         Used to resolve item_code → checklist_item_id.

    Returns:
        List of dicts, one per filled-in row:
            {
                "checklist_item_id": int,
                "item_code": str,
                "answer": str,          # "Yes" / "No" / "Partial" / "N/A"
                "rag_status": str,      # "green" / "red" / "amber" / "na"
                "comments": str | None,
                "evidence_links": list[str],
            }

    Raises:
        ValueError: If the sheet is missing or the format is unrecognisable.
    """
    import io
    wb = openpyxl.load_workbook(io.BytesIO(file_bytes), data_only=True)

    if _SHEET_NAME not in wb.sheetnames:
        raise ValueError(
            f"The uploaded file does not contain a '{_SHEET_NAME}' sheet. "
            "Please upload the Excel file that was generated by ReviewBot."
        )

    ws = wb[_SHEET_NAME]

    # Build a code → item lookup for fast matching
    code_to_item = {
        (getattr(item, "item_code", "") or "").strip(): item
        for item in checklist_items
    }

    results = []
    skipped_codes = []

    for row in ws.iter_rows(min_row=_DATA_START_ROW, values_only=True):
        item_code = str(row[0] or "").strip()
        raw_response = str(row[6] or "").strip() if row[6] else ""

        if not item_code:
            continue  # blank row

        if not raw_response:
            skipped_codes.append(item_code)
            continue  # reviewer left Response empty — skip silently

        # Normalise response
        normalised = raw_response.lower()
        if normalised not in _RAG_MAP:
            raise ValueError(
                f"Row with code '{item_code}' has an unrecognised response value: "
                f"'{raw_response}'. Allowed values: Yes, No, Partial, N/A."
            )

        rag_status = _RAG_MAP[normalised]

        # Match to DB item
        db_item = code_to_item.get(item_code)
        if db_item is None:
            # Try case-insensitive fallback
            db_item = next(
                (v for k, v in code_to_item.items() if k.lower() == item_code.lower()),
                None,
            )
        if db_item is None:
            # Item not found in checklist — skip with a note (non-fatal)
            skipped_codes.append(f"{item_code}(not found)")
            continue

        comments = str(row[7] or "").strip() or None
        raw_links = str(row[8] or "").strip()
        evidence_links = [ln.strip() for ln in raw_links.split(",") if ln.strip()] if raw_links else []

        results.append({
            "checklist_item_id": db_item.id,
            "item_code": item_code,
            "answer": raw_response,
            "rag_status": rag_status,
            "comments": comments,
            "evidence_links": evidence_links,
        })

    return results
