"""
Report Generator
Generates comprehensive review reports with compliance analysis
"""
from typing import Dict, List, Any, Optional
from datetime import datetime
from pathlib import Path
import markdown
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Heading
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from app.core.config import settings


class ReportGenerator:
    """Generate review reports in multiple formats"""
    
    def __init__(self):
        self.reports_dir = Path(settings.REPORTS_DIR)
        self.reports_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_markdown_report(self, report_data: Dict[str, Any]) -> str:
        """Generate markdown format report"""
        
        md_content = f"""# Project Review Report

## Executive Summary
- **Project:** {report_data.get('project_name', 'N/A')}
- **Review Date:** {report_data.get('review_date', datetime.now().strftime('%Y-%m-%d'))}
- **Overall RAG Status:** {self._get_rag_emoji(report_data.get('overall_rag_status', 'na'))} {report_data.get('overall_rag_status', 'N/A').upper()}
- **Compliance Score:** {report_data.get('compliance_score', 0):.1f}%
- **Participants:** {', '.join(report_data.get('participants', []))}

---

## {self._get_rag_emoji('green')} Areas Followed Well

{self._format_list(report_data.get('areas_followed', []))}

---

## {self._get_rag_emoji('red')} Gaps Identified

{self._format_gaps(report_data.get('gaps_identified', []))}

---

## 💡 Recommendations

{self._format_list(report_data.get('recommendations', []))}

---

## 📋 Action Items

{self._format_action_items(report_data.get('action_items', []))}

---

## Detailed Findings

{self._format_detailed_findings(report_data.get('detailed_findings', []))}

---

## Approval Status

**Status:** {report_data.get('approval_status', 'PENDING').upper()}

> ⚠️ This report requires human approval before distribution.

---

*Generated by AI Tech & Delivery Review Agent v{settings.APP_VERSION}*
*Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        
        # Save to file
        filename = f"report_{report_data.get('project_name', 'unknown').replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        file_path = self.reports_dir / filename
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        return str(file_path)
    
    def generate_pdf_report(self, report_data: Dict[str, Any]) -> str:
        """Generate PDF format report using ReportLab"""
        
        filename = f"report_{report_data.get('project_name', 'unknown').replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        file_path = self.reports_dir / filename
        
        doc = SimpleDocTemplate(
            str(file_path),
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a2e'),
            spaceAfter=30
        ))
        
        content = []
        
        # Title
        content.append(Paragraph("Project Review Report", styles['CustomTitle']))
        content.append(Spacer(1, 20))
        
        # Executive Summary
        summary_data = [
            ['Project', report_data.get('project_name', 'N/A')],
            ['Review Date', report_data.get('review_date', datetime.now().strftime('%Y-%m-%d'))],
            ['RAG Status', self._get_rag_emoji(report_data.get('overall_rag_status', 'na')) + 
             ' ' + (report_data.get('overall_rag_status', 'N/A') or 'N/A').upper()],
            ['Compliance Score', f"{report_data.get('compliance_score', 0):.1f}%"],
        ]
        
        summary_table = Table(summary_data, colWidths=[150, 300])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#000000')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc'))
        ]))
        
        content.append(summary_table)
        content.append(Spacer(1, 30))
        
        # Areas Followed Well
        content.append(Paragraph("Areas Followed Well", styles['Heading2']))
        for area in report_data.get('areas_followed', []):
            content.append(Paragraph(f"• {area}", styles['Normal']))
        content.append(Spacer(1, 20))
        
        # Gaps Identified
        content.append(Paragraph("Gaps Identified", styles['Heading2']))
        for gap in report_data.get('gaps_identified', []):
            content.append(Paragraph(f"🔴 {gap.get('title', 'Gap')}", styles['Normal']))
            if isinstance(gap, dict) and gap.get('description'):
                content.append(Paragraph(f"   {gap['description']}", styles['Normal']))
        content.append(Spacer(1, 20))
        
        # Recommendations
        content.append(Paragraph("Recommendations", styles['Heading2']))
        for rec in report_data.get('recommendations', []):
            content.append(Paragraph(f"💡 {rec}", styles['Normal']))
        content.append(Spacer(1, 20))
        
        # Action Items
        content.append(Paragraph("Action Items", styles['Heading2']))
        action_items = report_data.get('action_items', [])
        if action_items:
            action_data = [['Item', 'Owner', 'Due Date', 'Priority']]
            for item in action_items:
                action_data.append([
                    item.get('item', 'N/A'),
                    item.get('owner', 'TBD'),
                    item.get('due_date', 'TBD'),
                    item.get('priority', 'Medium')
                ])
            
            action_table = Table(action_data, colWidths=[200, 120, 100, 80])
            action_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a1a2e')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc'))
            ]))
            content.append(action_table)
        
        # Build PDF
        doc.build(content)
        
        return str(file_path)
    
    def calculate_compliance_score(
        self,
        responses: List[Dict[str, Any]],
        checklist_items: List[Dict[str, Any]]
    ) -> float:
        """
        Calculate overall compliance score based on responses
        Returns score 0-100
        """
        if not responses:
            return 0.0
        
        total_weight = 0
        weighted_score = 0
        
        rag_scores = {
            'green': 100,
            'amber': 50,
            'red': 0,
            'na': None  # Exclude from calculation
        }
        
        for response in responses:
            rag = response.get('rag_status', 'na').lower()
            weight = response.get('weight', 1.0)
            
            score = rag_scores.get(rag)
            if score is not None:
                weighted_score += score * weight
                total_weight += weight
        
        if total_weight == 0:
            return 0.0
        
        return (weighted_score / total_weight)
    
    def determine_overall_rag(self, compliance_score: float) -> str:
        """Determine overall RAG status based on compliance score"""
        if compliance_score >= 80:
            return 'green'
        elif compliance_score >= 50:
            return 'amber'
        else:
            return 'red'
    
    def analyze_gaps(
        self,
        responses: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Analyze responses to identify gaps"""
        gaps = []
        
        for response in responses:
            rag = response.get('rag_status', 'na').lower()
            
            if rag in ['red', 'amber']:
                gaps.append({
                    'title': response.get('question', 'Unknown'),
                    'description': response.get('comments', ''),
                    'rag_status': rag,
                    'area': response.get('area', 'General'),
                    'severity': 'high' if rag == 'red' else 'medium'
                })
        
        return gaps
    
    def generate_action_items(
        self,
        gaps: List[Dict[str, Any]],
        participants: List[str]
    ) -> List[Dict[str, Any]]:
        """Generate action items from identified gaps"""
        action_items = []
        
        for idx, gap in enumerate(gaps, 1):
            action_items.append({
                'item': f"Address: {gap['title']}",
                'owner': 'TBD',
                'due_date': 'TBD',
                'priority': gap.get('severity', 'medium').capitalize(),
                'related_gap': gap['title']
            })
        
        return action_items
    
    def _get_rag_emoji(self, rag_status: str) -> str:
        """Get emoji for RAG status"""
        emojis = {
            'green': '🟢',
            'amber': '🟡',
            'red': '🔴',
            'na': '⚪'
        }
        return emojis.get(rag_status.lower(), '⚪')
    
    def _format_list(self, items: List[Any]) -> str:
        """Format list items for markdown"""
        if not items:
            return "*No items*"
        
        return "\n".join([f"✅ {item}" if isinstance(item, str) else f"✅ {item.get('title', 'Item')}" 
                         for item in items])
    
    def _format_gaps(self, gaps: List[Dict[str, Any]]) -> str:
        """Format gaps for markdown"""
        if not gaps:
            return "*No gaps identified*"
        
        formatted = []
        for gap in gaps:
            title = gap.get('title', 'Unknown Gap')
            desc = gap.get('description', '')
            severity = gap.get('severity', 'medium')
            emoji = '🔴' if severity == 'high' else '🟡'
            
            formatted.append(f"{emoji} **{title}**")
            if desc:
                formatted.append(f"   {desc}")
        
        return "\n\n".join(formatted)
    
    def _format_action_items(self, items: List[Dict[str, Any]]) -> str:
        """Format action items for markdown"""
        if not items:
            return "*No action items*"
        
        lines = ["| Item | Owner | Due Date | Priority |", "|------|-------|----------|----------|"]
        
        for item in items:
            lines.append(
                f"| {item.get('item', 'N/A')} | {item.get('owner', 'TBD')} | "
                f"{item.get('due_date', 'TBD')} | {item.get('priority', 'Medium')} |"
            )
        
        return "\n".join(lines)
    
    def _format_detailed_findings(self, findings: List[Dict[str, Any]]) -> str:
        """Format detailed findings section"""
        if not findings:
            return "*No detailed findings*"
        
        formatted = []
        for finding in findings:
            formatted.append(f"### {finding.get('area', 'Area')}")
            formatted.append(finding.get('description', ''))
            formatted.append("")
        
        return "\n".join(formatted)


# Global instance
_report_generator: Optional[ReportGenerator] = None


def get_report_generator() -> ReportGenerator:
    """Get or create report generator instance"""
    global _report_generator
    if _report_generator is None:
        _report_generator = ReportGenerator()
    return _report_generator
