"""Initial v2.0 schema - 21 tables

Revision ID: 001
Revises: 
Create Date: 2026-03-27

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True, default='reviewer'),
    sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    
    # Projects table
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stakeholders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, default='active'),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True, default='medium'),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Project Members table
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('persona', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
    sa.Column('joined_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', 'persona', name='unique_project_user_persona')
    )
    
    # Checklists table
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True, default='1.0'),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True, default=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Checklist Items table (enhanced for autonomous review)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True, default=1.0),
    sa.Column('is_required', sa.Boolean(), nullable=True, default=True),
    sa.Column('expected_evidence', sa.Text(), nullable=True),
    sa.Column('review_type', sa.String(length=50), nullable=True, default='human'),
    sa.Column('data_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('can_override', sa.Boolean(), nullable=True, default=True),
    sa.Column('override_requires_approval', sa.Boolean(), nullable=True, default=False),
    sa.Column('override_approver_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_for_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True, default=0),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Review Sessions table
    op.create_table('review_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('review_type', sa.String(length=50), nullable=False),
    sa.Column('review_mode', sa.String(length=50), nullable=True),
    sa.Column('conducted_by', sa.Integer(), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_date', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('status', sa.String(length=50), nullable=True, default='draft'),
    sa.Column('voice_enabled', sa.Boolean(), nullable=True, default=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.ForeignKeyConstraint(['conducted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Recurring Review Schedules table
    op.create_table('recurring_review_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=True),
    sa.Column('time_of_day', sa.Time(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('review_mode', sa.String(length=50), nullable=True),
    sa.Column('participant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Milestone Review Triggers table
    op.create_table('milestone_review_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('milestone_name', sa.String(length=255), nullable=False),
    sa.Column('trigger_event', sa.String(length=255), nullable=True),
    sa.Column('timing_offset_days', sa.Integer(), nullable=True),
    sa.Column('review_mode', sa.String(length=50), nullable=True),
    sa.Column('participant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True, default=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Review Instances table
    op.create_table('review_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('milestone_trigger_id', sa.Integer(), nullable=True),
    sa.Column('review_type', sa.String(length=50), nullable=True),
    sa.Column('scheduled_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('completed_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, default='scheduled'),
    sa.Column('review_mode', sa.String(length=50), nullable=True),
    sa.Column('overall_readiness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['milestone_trigger_id'], ['milestone_review_triggers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['recurring_review_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Self-Review Sessions table
    op.create_table('self_review_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_session_id', sa.Integer(), nullable=True),
    sa.Column('persona', sa.String(length=100), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('readiness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, default='pending'),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Autonomous Review Results table
    op.create_table('autonomous_review_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=True),
    sa.Column('review_session_id', sa.Integer(), nullable=True),
    sa.Column('autonomous_rag', sa.String(length=50), nullable=False),
    sa.Column('autonomous_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('autonomous_notes', sa.Text(), nullable=True),
    sa.Column('execution_time_seconds', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Human Review Results table
    op.create_table('human_review_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=True),
    sa.Column('review_session_id', sa.Integer(), nullable=True),
    sa.Column('human_rag', sa.String(length=50), nullable=False),
    sa.Column('human_comments', sa.Text(), nullable=True),
    sa.Column('human_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Override Requests table
    op.create_table('override_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autonomous_result_id', sa.Integer(), nullable=True),
    sa.Column('human_result_id', sa.Integer(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=True, default=False),
    sa.Column('approver_role_required', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, default='pending'),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('decided_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['autonomous_result_id'], ['autonomous_review_results.id'], ),
    sa.ForeignKeyConstraint(['human_result_id'], ['human_review_results.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Override Approvals table
    op.create_table('override_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('override_request_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approver_role', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['override_request_id'], ['override_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Final Review Results table
    op.create_table('final_review_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=True),
    sa.Column('review_session_id', sa.Integer(), nullable=True),
    sa.Column('autonomous_rag', sa.String(length=50), nullable=True),
    sa.Column('human_rag', sa.String(length=50), nullable=True),
    sa.Column('final_rag', sa.String(length=50), nullable=False),
    sa.Column('is_overridden', sa.Boolean(), nullable=True, default=False),
    sa.Column('override_request_id', sa.Integer(), nullable=True),
    sa.Column('final_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['override_request_id'], ['override_requests.id'], ),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Consolidated Self-Review Reports table
    op.create_table('consolidated_self_review_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('review_session_id', sa.Integer(), nullable=True),
    sa.Column('overall_readiness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('persona_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cross_persona_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Reminder Queue table
    op.create_table('reminder_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_instance_id', sa.Integer(), nullable=True),
    sa.Column('reminder_type', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, default='pending'),
    sa.Column('recipient_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True, default=0),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['review_instance_id'], ['review_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Meeting Blocks table
    op.create_table('meeting_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_instance_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('blocked_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('unblocked_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('blocked_by', sa.Integer(), nullable=True),
    sa.Column('unblocked_by', sa.Integer(), nullable=True),
    sa.Column('override_approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, default='active'),
    sa.ForeignKeyConstraint(['review_instance_id'], ['review_instances.id'], ),
    sa.ForeignKeyConstraint(['blocked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unblocked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['override_approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Stakeholder Preparation table
    op.create_table('stakeholder_preparation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_instance_id', sa.Integer(), nullable=True),
    sa.Column('stakeholder_id', sa.Integer(), nullable=True),
    sa.Column('preparation_pack_sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('preparation_pack_viewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('readiness_score_viewed', sa.Boolean(), nullable=True, default=False),
    sa.Column('suggested_questions_viewed', sa.Boolean(), nullable=True, default=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True, default=False),
    sa.Column('acknowledged_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['review_instance_id'], ['review_instances.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Review Trend Analytics table
    op.create_table('review_trend_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('team_member_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('avg_readiness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_trend', sa.String(length=50), nullable=True),
    sa.Column('recurring_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_member_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Gap Tracking table
    op.create_table('gap_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('first_identified_review_id', sa.Integer(), nullable=True),
    sa.Column('gap_description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, default='open'),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('identified_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('appeared_in_review_count', sa.Integer(), nullable=True, default=1),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_identified_review_id'], ['review_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes
    op.create_index('idx_project_members_project', 'project_members', ['project_id'])
    op.create_index('idx_project_members_user', 'project_members', ['user_id'])
    op.create_index('idx_project_members_persona', 'project_members', ['persona'])
    op.create_index('idx_checklist_items_checklist', 'checklist_items', ['checklist_id'])
    op.create_index('idx_checklist_items_review_type', 'checklist_items', ['review_type'])
    op.create_index('idx_review_sessions_project', 'review_sessions', ['project_id'])
    op.create_index('idx_review_sessions_status', 'review_sessions', ['status'])
    op.create_index('idx_recurring_schedules_project', 'recurring_review_schedules', ['project_id'])
    op.create_index('idx_review_instances_scheduled', 'review_instances', ['scheduled_date'])
    op.create_index('idx_review_instances_status', 'review_instances', ['status'])
    op.create_index('idx_self_review_sessions_review', 'self_review_sessions', ['review_session_id'])
    op.create_index('idx_autonomous_results_session', 'autonomous_review_results', ['review_session_id'])
    op.create_index('idx_human_results_session', 'human_review_results', ['review_session_id'])
    op.create_index('idx_override_requests_status', 'override_requests', ['status'])
    op.create_index('idx_final_results_session', 'final_review_results', ['review_session_id'])
    op.create_index('idx_reminder_queue_scheduled', 'reminder_queue', ['scheduled_at'])
    op.create_index('idx_reminder_queue_status', 'reminder_queue', ['status'])
    op.create_index('idx_meeting_blocks_status', 'meeting_blocks', ['status'])
    op.create_index('idx_stakeholder_prep_instance', 'stakeholder_preparation', ['review_instance_id'])
    op.create_index('idx_trend_analytics_project', 'review_trend_analytics', ['project_id'])
    op.create_index('idx_trend_analytics_period', 'review_trend_analytics', ['period_start', 'period_end'])
    op.create_index('idx_gap_tracking_project', 'gap_tracking', ['project_id'])
    op.create_index('idx_gap_tracking_status', 'gap_tracking', ['status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gap_tracking_status', table_name='gap_tracking')
    op.drop_index('idx_gap_tracking_project', table_name='gap_tracking')
    op.drop_index('idx_trend_analytics_period', table_name='review_trend_analytics')
    op.drop_index('idx_trend_analytics_project', table_name='review_trend_analytics')
    op.drop_index('idx_stakeholder_prep_instance', table_name='stakeholder_preparation')
    op.drop_index('idx_meeting_blocks_status', table_name='meeting_blocks')
    op.drop_index('idx_reminder_queue_status', table_name='reminder_queue')
    op.drop_index('idx_reminder_queue_scheduled', table_name='reminder_queue')
    op.drop_index('idx_final_results_session', table_name='final_review_results')
    op.drop_index('idx_override_requests_status', table_name='override_requests')
    op.drop_index('idx_human_results_session', table_name='human_review_results')
    op.drop_index('idx_autonomous_results_session', table_name='autonomous_review_results')
    op.drop_index('idx_self_review_sessions_review', table_name='self_review_sessions')
    op.drop_index('idx_review_instances_status', table_name='review_instances')
    op.drop_index('idx_review_instances_scheduled', table_name='review_instances')
    op.drop_index('idx_recurring_schedules_project', table_name='recurring_review_schedules')
    op.drop_index('idx_review_sessions_status', table_name='review_sessions')
    op.drop_index('idx_review_sessions_project', table_name='review_sessions')
    op.drop_index('idx_checklist_items_review_type', table_name='checklist_items')
    op.drop_index('idx_checklist_items_checklist', table_name='checklist_items')
    op.drop_index('idx_project_members_persona', table_name='project_members')
    op.drop_index('idx_project_members_user', table_name='project_members')
    op.drop_index('idx_project_members_project', table_name='project_members')
    op.drop_table('gap_tracking')
    op.drop_table('review_trend_analytics')
    op.drop_table('stakeholder_preparation')
    op.drop_table('meeting_blocks')
    op.drop_table('reminder_queue')
    op.drop_table('consolidated_self_review_reports')
    op.drop_table('final_review_results')
    op.drop_table('override_approvals')
    op.drop_table('override_requests')
    op.drop_table('human_review_results')
    op.drop_table('autonomous_review_results')
    op.drop_table('self_review_sessions')
    op.drop_table('review_instances')
    op.drop_table('milestone_review_triggers')
    op.drop_table('recurring_review_schedules')
    op.drop_table('review_sessions')
    op.drop_table('checklist_items')
    op.drop_table('checklists')
    op.drop_table('project_members')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
