import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

TECHNICAL_ITEMS = [
    # Architecture & Design
    ("1.1","Architecture & Design","Who is responsible for the architecture and design?","Architecture RACI in project governance doc or /docs/; named architect with contact details; org chart section showing architecture ownership and accountability chain"),
    ("1.2","Architecture & Design","Is the target architecture documented and up to date (context, container, component, deployment diagrams)?","Architecture diagrams (C4 context/container/component/deployment) in /docs/ or Confluence, versioned in Git, updated within last 3 months; diagram source files (.drawio, .puml, Lucidchart) accessible"),
    ("1.3","Architecture & Design","Are HLD and LLD available for all key modules and services?","HLD.md and LLD.md (or equivalent) in /docs/ per module or service; linked from README; last commit date within 3 months; covers all services in scope"),
    ("1.4","Architecture & Design","Are architectural decisions and trade-offs documented and aligned with business and technical requirements?","Architecture Decision Records (ADRs) in /docs/adr/ or Confluence; each ADR covers context, decision, and consequences; at least one ADR per major technology or design choice"),
    ("1.5","Architecture & Design","Is the design modular, loosely coupled, scalable and maintainable?","Architecture diagram showing clear service/module boundaries; no circular dependencies (verified via static analysis); coupling metrics from SonarQube below threshold; modularity described in design doc"),
    ("1.6","Architecture & Design","Are appropriate design patterns and reference architectures consistently applied?","Design patterns listed in architecture doc or README; reference architecture diagram aligned to enterprise standards; pattern usage verifiable in codebase folder structure"),
    ("1.7","Architecture & Design","Is there a clear separation of concerns (UI, API, business logic, data, integration, cross-cutting services)?","Layer diagram showing UI/API/business logic/data separation; folder structure in repo matching layered or clean architecture; no cross-layer direct dependencies in dependency graph"),
    ("1.8","Architecture & Design","Is the integration approach (APIs, messaging, microservices, batch/ETL) clearly defined and consistent?","Integration architecture diagram showing all inbound/outbound APIs, messaging, and ETL flows in /docs/; API contracts or AsyncAPI spec in repository; integration design reviewed and approved"),
    ("1.9","Architecture & Design","Are cross-cutting concerns (configuration, logging, security, caching, observability) addressed in the design?","Cross-cutting concerns section in architecture doc covering logging, security, caching, observability, and configuration; corresponding shared libraries or middleware in codebase"),
    ("1.10","Architecture & Design","Are non-functional requirements (performance, availability, reliability, security, compliance) captured and designed for?","NFR document with quantified SLOs for performance (P99 latency), availability (%), and reliability (MTTR); traceability from each NFR to a design decision in architecture doc"),
    ("1.11","Architecture & Design","Are chosen technologies and platforms modern, supportable and aligned with enterprise standards and roadmap?","Technology radar or approved stack list from enterprise architecture; dependency versions within 2 major versions of latest stable; no end-of-life components without a documented waiver"),
    ("1.12","Architecture & Design","Are deprecated or legacy components identified with a containment or migration plan?","Technical debt register with deprecated components listed; migration plan with target dates in Jira or Confluence; no deprecated components being newly extended without approved exception"),

    # Technical Documentation
    ("2.1","Technical Documentation","Is system design and architecture documentation complete, accurate and version-controlled?","Architecture docs in /docs/ committed to Git with commit history; Confluence space with versioned pages and last-modified dates; no orphaned diagrams stored only in chat tools"),
    ("2.2","Technical Documentation","Is API documentation (Swagger/OpenAPI, Postman collections, AsyncAPI) current and accessible to consumers?","Swagger/OpenAPI spec at /docs or /api/openapi.yaml; Postman collection in repo /docs/api/; AsyncAPI spec for event-driven interfaces; documentation auto-generated from code annotations where possible"),
    ("2.3","Technical Documentation","Are installation, deployment and configuration steps clearly documented and validated on a clean environment?","README.md with local setup instructions validated by a new team member; deployment runbook in /docs/deploy/; config parameters table with descriptions, defaults, and required/optional flag"),
    ("2.4","Technical Documentation","Is developer onboarding documentation available (local setup, coding standards, workflows)?","DEVELOPER.md or onboarding guide in repo root or /docs/; covers local setup, branching strategy, coding standards, and PR process; validated by last new joiner within past 3 months"),
    ("2.5","Technical Documentation","Is user, admin and support documentation (SOPs, FAQs, runbooks) available where needed?","User guide in /docs/user/ or Confluence; admin runbook with configuration and access procedures; support FAQ or troubleshooting guide accessible to operations team without repo access"),
    ("2.6","Technical Documentation","Are data models, ER diagrams and integration contracts documented and kept in sync with implementation?","ER diagram (dbdiagram, draw.io, or similar) in /docs/; schema migration scripts in /db/migrations/; integration contracts (OpenAPI/AsyncAPI) in /contracts/; all updated within last 2 months"),
    ("2.7","Technical Documentation","Are known issues, limitations and technical debt items documented with owners and target dates?","KNOWN_ISSUES.md or Confluence technical debt page with description, owner, and target resolution date; Jira technical debt epic with story-pointed items; no undocumented known production issues"),

    # Data & Storage Design
    ("3.1","Data & Storage Design","Are data models and DB schemas appropriate for the workload and aligned to domain concepts?","ER diagram showing normalized schema (3NF or documented exceptions); schema migration files in /db/migrations/ using Alembic/Flyway/Liquibase; schema aligned to domain concepts, no generic tables"),
    ("3.2","Data & Storage Design","Are indexing, partitioning and sharding strategies adequate for expected scale and query patterns?","Database performance test results showing query P99 latency within NFR; EXPLAIN ANALYZE output for top queries in /docs/performance/; index list per table documented with rationale"),
    ("3.3","Data & Storage Design","Are critical queries reviewed and optimized using execution plans and performance metrics?","Query performance analysis report with EXPLAIN ANALYZE results; no full table scans on tables > 100k rows (verified via slow query log); optimization tickets in Jira with resolution evidence"),
    ("3.4","Data & Storage Design","Are backup and restore strategies defined, tested and documented for each data store?","Backup policy document with RPO/RTO targets; backup schedule in DB console or IaC config; restore drill record with completion time vs RTO target from within last 3 months"),
    ("3.5","Data & Storage Design","Are data retention, archival and purging policies defined and implemented in line with compliance needs?","Data retention policy document aligned to legal/compliance requirements; archival or purging job in /scripts/ or scheduled task; retention periods defined per data class and tested"),
    ("3.6","Data & Storage Design","Is database security in place (RBAC, least privilege, encryption at rest, network controls, masking where needed)?","DB access control matrix showing least-privilege roles; encryption-at-rest enabled in DB console or IaC config; network firewall rules restricting DB port to app tier only; no shared credentials"),
    ("3.7","Data & Storage Design","Is replication or high availability configured where required?","DB HA configuration in IaC (multi-AZ, read replica, or cluster); failover test record showing switchover time within RTO; monitoring alert configured on replica lag"),
    ("3.8","Data & Storage Design","Is data migration or integration strategy defined, including mapping, reconciliation and cutover plans?","Data migration plan document with source-to-target mapping, reconciliation approach, and cutover runbook; test migration results in staging; rollback procedure documented and tested"),
    ("3.9","Data & Storage Design","Are data quality checks and constraints in place (not-null, referential integrity, validation rules)?","Database constraint definitions (NOT NULL, FK, CHECK, UNIQUE) in schema scripts; data validation layer in application code; data quality test suite or checks in ETL pipeline verified"),

    # Security Architecture
    ("4.1","Security Architecture","Is sensitive data (passwords, tokens, keys, PII, financial data) encrypted in transit and at rest?","TLS 1.2+ enforced on all endpoints (SSL Labs grade A); DB encryption-at-rest enabled in cloud console or IaC; encryption key management via KMS/Vault; no plaintext secrets in config files or Git"),
    ("4.2","Security Architecture","Are authentication mechanisms aligned with enterprise standards (SSO, OAuth2/OIDC, MFA where required)?","SSO/OIDC/OAuth2 integration config in codebase; MFA enabled for privileged accounts (screenshot from IAM console); authentication flow diagram in architecture doc; token expiry and refresh handled correctly"),
    ("4.3","Security Architecture","Is authorization based on least privilege using well-defined roles and permissions (RBAC/ABAC)?","Role definition document with permissions matrix; RBAC/ABAC implementation in code (middleware or decorator pattern); access review records from last 3 months showing no over-provisioning"),
    ("4.4","Security Architecture","Are secrets stored in an approved secrets vault and never hardcoded or committed to source control?","Secrets manager config (AWS Secrets Manager/Azure Key Vault/HashiCorp Vault) in IaC; git-secrets or pre-commit hook preventing credential commits; SAST scan showing no hardcoded secrets in codebase"),
    ("4.5","Security Architecture","Are input validation, output encoding and security headers implemented to prevent common attacks?","Input validation middleware or library in codebase (e.g., Pydantic, Joi, class-validator); security headers verified via securityheaders.com scan (grade A); OWASP dependency check report clean"),
    ("4.6","Security Architecture","Are checks in place for common vulnerabilities (XSS, SQL injection, CSRF, SSRF, insecure deserialization)?","SAST scan report (SonarQube/Checkmarx/Semgrep) with no critical or high-severity findings; DAST scan results (OWASP ZAP) against staging environment; pen test report from last 12 months if applicable"),
    ("4.7","Security Architecture","Are third-party dependencies and container images regularly scanned and updated for vulnerabilities?","SCA/SBOM report (Snyk/Dependabot/Black Duck) with no unresolved critical CVEs; container image scan in CI pipeline (Trivy/Grype); automated dependency update policy enforced via Dependabot or Renovate"),
    ("4.8","Security Architecture","Is HTTPS/TLS enforced for all external and internal communications where appropriate?","TLS certificate in load balancer or ingress config (IaC); HTTP-to-HTTPS redirect configured; HSTS header present; certificate expiry monitoring alert configured with at least 30-day lead time"),
    ("4.9","Security Architecture","Are security-relevant events logged without leaking sensitive data?","Audit log entries for auth events, privilege changes, and data access in logging platform; log sample showing no PII or secrets in log lines; log retention period meeting compliance requirements"),
    ("4.10","Security Architecture","Are security reviews and tests (SAST, DAST, penetration tests where applicable) planned and tracked?","Security testing plan in project schedule; SAST/DAST results in CI pipeline with gating policy; open security findings tracked in Jira with owner and target resolution date; no findings suppressed without exception"),

    # Code Quality & Standards
    ("5.1","Code Quality & Standards","Is the codebase following agreed coding standards, naming conventions and folder structure?","CONTRIBUTING.md or coding standards doc in repo; linter config (.eslintrc, .pylintrc, ruff.toml) committed to repo; CI pipeline enforcing linter with zero critical violations before merge"),
    ("5.2","Code Quality & Standards","Are peer reviews or pull-request reviews performed for all non-trivial changes?","Branch protection rules requiring at least 1 reviewer before merge (GitHub/GitLab settings); PR history showing reviews on last 20 merged PRs; PR template with review checklist in .github/"),
    ("5.3","Code Quality & Standards","Are hardcoded values, credentials and environment-specific parameters avoided and externalized to configuration or vaults?","No secrets in git history (git-secrets scan clean); config externalized to environment variables or secrets vault; .env.example file in repo showing all required variables without values"),
    ("5.4","Code Quality & Standards","Is error handling consistent, with meaningful messages and no silent failures?","Central error handler or middleware in codebase; error response schema documented in OpenAPI spec; no unhandled promise rejections or uncaught exceptions in last 7 days of application logs"),
    ("5.5","Code Quality & Standards","Are reusable components and shared libraries used instead of copy-paste and duplication?","Shared library or module directory in repo (e.g., /shared/, /common/, /libs/); SonarQube duplication check showing code duplication below threshold; component library documented with usage examples"),
    ("5.6","Code Quality & Standards","Are unit tests present for core logic with meaningful assertions and acceptable coverage?","Test directory structure matching source; CI pipeline showing test run with pass rate; coverage report showing >= 80% line coverage on core business logic modules; assertions test behaviour not implementation"),
    ("5.7","Code Quality & Standards","Is version control used effectively (branching strategy, tagging, pull requests, release branches)?","Branching strategy documented in CONTRIBUTING.md; Git history showing PR-based workflow with no direct pushes to main; release tags following semver in Git; feature branch naming convention followed"),
    ("5.8","Code Quality & Standards","Are static analysis tools and linters enabled and free of critical issues before merging?","Linter and SAST tool configured in CI pipeline; pipeline failing build on critical violations; SonarQube quality gate set to 'Passed' required before merge; no suppressed warnings without documented reason"),
    ("5.9","Code Quality & Standards","Is dead code, unused configuration and feature flags regularly cleaned up?","SonarQube report showing zero blocker/critical dead-code issues; PR history showing cleanup commits; feature flag registry with expiry dates and process for retiring old flags"),
    ("5.10","Code Quality & Standards","Is the code structured to support testability and extension (dependency injection, interfaces, clear boundaries)?","Dependency injection pattern used with no hardcoded dependencies in constructors; interface or abstract class definitions for mockable components; test coverage metrics accessible in CI dashboard"),

    # Testing & Coverage
    ("6.1","Testing & Coverage","Is there a documented test strategy covering unit, integration, system, UAT, regression and smoke tests?","Test strategy document in /docs/testing/ covering scope, test types, tools, entry/exit criteria, and sign-off; reviewed and approved by QA lead and project manager"),
    ("6.2","Testing & Coverage","Are test cases, test data and expected results documented and traceable to requirements or user stories?","Test cases in XRAY/TestRail/Zephyr or /tests/ directory with descriptive names and expected results; test data scripts in /tests/fixtures/; traceability matrix linking tests to requirements or stories"),
    ("6.3","Testing & Coverage","Are automated test suites integrated with CI/CD and run on every build or pull request for critical components?","CI pipeline config (.github/workflows/, Jenkinsfile) running automated tests on every PR; test results published in pipeline artifacts; no test skips without documented justification in PR"),
    ("6.4","Testing & Coverage","Is test coverage measured and are minimum thresholds defined for important modules?","Coverage report in CI artifacts (Istanbul/JaCoCo/pytest-cov); coverage threshold enforced in CI config (e.g., --cov-fail-under=80); coverage trend chart in code quality tool showing stable or improving trend"),
    ("6.5","Testing & Coverage","Are non-functional tests (performance, load, soak, security, failover) planned and executed where required?","Performance test scripts in /tests/performance/ (JMeter/k6/Gatling); load test results against NFR targets; security test report; failover test record in /docs/testing/ from last 3 months"),
    ("6.6","Testing & Coverage","Are test environments representative of production in terms of configuration and integrations?","Environment parity checklist; staging environment spec matching production (same DB version, OS, external integrations); no production-only configurations absent from staging environment"),
    ("6.7","Testing & Coverage","Is defect tracking in place with clear ownership, priority and resolution SLAs?","Defect tracker in Jira/Azure DevOps with severity, priority, owner, and target fix date fields populated; SLA policy document for defect resolution; defect age report showing no unresolved SLA breaches"),

    # DevSecOps
    ("7.1","DevSecOps","Is a CI/CD pipeline implemented for build, test, security scans and deployment?","Pipeline definition file in repo (.github/workflows/, Jenkinsfile, azure-pipelines.yml, .gitlab-ci.yml); pipeline stages showing build, test, security scan, and deploy; last successful run record visible"),
    ("7.2","DevSecOps","Are environment configurations (Dev, QA, Pre-Prod, Prod) parameterized, separated and managed securely?","Environment-specific config in separate parameter files or secrets vault; IaC showing environment-specific variables; no .env files with real secrets committed to repo; config review process in place"),
    ("7.3","DevSecOps","Is a clear rollback or hotfix strategy defined and tested for failed deployments?","Rollback procedure in deployment runbook; blue/green or canary deployment config in IaC; rollback test record from within last 3 months; hotfix branching strategy documented in CONTRIBUTING.md"),
    ("7.4","DevSecOps","Is infrastructure-as-code (Terraform, ARM/Bicep, CloudFormation, Ansible, Helm) used where applicable?","Terraform/ARM/Bicep/CloudFormation/Helm files in /infra/ or /deploy/ directory; IaC plan showing all managed resources; state file stored remotely (Terraform Cloud/Azure backend/S3)"),
    ("7.5","DevSecOps","Are deployment scripts, IaC templates and pipeline definitions version-controlled and peer-reviewed?","Pipeline and IaC files committed in same Git repo as application code; PR history showing reviews of pipeline changes; no manual pipeline configuration changes without corresponding IaC update"),
    ("7.6","DevSecOps","Are SAST, DAST, software composition analysis and container image scans integrated into pipelines with gating policies?","Security scan stages in CI pipeline config; pipeline gating policy set to fail on critical findings; scan reports in pipeline artifacts; no critical findings suppressed without documented exception process"),
    ("7.7","DevSecOps","Are secrets and credentials in pipelines managed through a secure secrets store and never embedded in code?","Pipeline secrets configured in GitHub Secrets/Azure Key Vault/Jenkins Credentials store; no secrets visible in pipeline logs (verified in last 5 run logs); secrets rotation policy documented"),
    ("7.8","DevSecOps","Are backups, restore procedures and DR runbooks validated through regular drills or simulations?","DR runbook in /docs/operations/; backup restore drill record from last 3 months with actual RTO achieved; DR test schedule in project calendar; results reviewed and gaps actioned"),
    ("7.9","DevSecOps","Are CI/CD tools themselves secured with access control, audit trails and least-privilege permissions?","CI/CD tool access matrix showing least-privilege roles; audit log enabled in GitHub/Jenkins/Azure DevOps; service accounts used for deployments with no personal credentials embedded in pipelines"),

    # Environments & Infrastructure
    ("8.1","Environments & Infrastructure","Is Dev/QA/UAT/Pre-Prod/Prod parity maintained for key components and configurations?","Environment comparison matrix in /docs/environments/; IaC showing consistent configuration across environments; no environment-specific hacks or workarounds in application code"),
    ("8.2","Environments & Infrastructure","Are environments provisioned and updated via IaC and configuration management tools?","All environment resources defined in Terraform/ARM/Ansible; no manually provisioned resources (IaC drift detection clean); environment provisioning pipeline tested and documented"),
    ("8.3","Environments & Infrastructure","Are capacities right-sized with headroom for growth and peak loads, and is auto-scaling used where relevant?","Infrastructure sizing document with peak load projections; auto-scaling policy defined in IaC with min/max/target thresholds; load test results confirming capacity under projected peak scenarios"),
    ("8.4","Environments & Infrastructure","Are recent build or environment failures analyzed with RCA and corrective actions tracked?","Incident log or build failure analysis in Confluence; RCA documents for last 3 incidents with root cause and corrective actions; corrective action tickets in Jira with status and owner"),
    ("8.5","Environments & Infrastructure","Are high-availability and resilience mechanisms in place (clusters, load balancers, multi-AZ or multi-node)?","HA architecture diagram showing multi-AZ/multi-node topology; cluster or load balancer configuration in IaC; failover test record showing successful switchover within agreed RTO; SLO uptime report"),
    ("8.6","Environments & Infrastructure","Are network configurations (VPC/VNet, firewalls, security groups, ingress/egress rules, VPN) reviewed and documented?","Network architecture diagram showing VPC/VNet, subnets, security groups, and firewall rules in /docs/; IaC defining all network resources; network access review records from last 3 months"),
    ("8.7","Environments & Infrastructure","Are environment-specific settings externalized and managed securely (no secrets in flat files checked into Git)?","No environment-specific values hardcoded in source code; config injected via environment variables or secrets vault at runtime; .env files excluded via .gitignore and confirmed absent from git history"),

    # Operational Readiness & Reliability
    ("9.1","Operational Readiness & Reliability","Is centralized, structured logging in place with correlation IDs to trace requests across services?","Logging framework configured (ELK/Datadog/CloudWatch/Splunk); structured JSON log format with correlation-id field; sample log trace showing a full request correlation across all involved services"),
    ("9.2","Operational Readiness & Reliability","Are metrics and dashboards defined for key SLIs such as latency, error rate, throughput and resource usage?","Observability dashboard (Grafana/Datadog/CloudWatch) showing latency P50/P95/P99, error rate, throughput, and resource utilization; SLO/SLI targets defined in runbook and visible on dashboard"),
    ("9.3","Operational Readiness & Reliability","Are alerts configured with meaningful thresholds, noise reduction and linked runbooks?","Alerting rules in monitoring tool for SLO breach, error rate spike, and resource exhaustion; alert runbook linked in each alert definition; on-call rotation configured in PagerDuty/OpsGenie"),
    ("9.4","Operational Readiness & Reliability","Is there a clear on-call model and escalation matrix for production incidents?","On-call schedule in PagerDuty/OpsGenie covering all production hours with backup coverage; escalation matrix document with contact details and response SLA per severity level"),
    ("9.5","Operational Readiness & Reliability","Are support processes, SOPs, runbooks and troubleshooting guides documented and maintained?","Runbooks in /docs/operations/ for common failure scenarios; SOP documents for routine operational tasks; troubleshooting FAQ accessible to support team without requiring repo access"),
    ("9.6","Operational Readiness & Reliability","Has the system passed an agreed go-live or operational readiness checklist?","Signed operational readiness checklist covering monitoring, backups, DR, security, and support; go-live approval email from operations lead; no open P1/P2 items at time of go-live"),
    ("9.7","Operational Readiness & Reliability","Are incident management and RCA processes defined with follow-up actions for recurring issues?","Incident management process document covering severity levels, response times, and communication templates; post-incident review records for last 3 incidents; recurring incident trend tracked and actioned"),

    # Compliance & Governance
    ("10.1","Compliance & Governance","Are licensing requirements for all third-party tools, libraries and platforms understood and compliant?","OSS licence scan report (FOSSA/Black Duck/SPDX SBOM) with no licence violations; approved software list from IT or enterprise architecture; commercial licence inventory with renewal dates"),
    ("10.2","Compliance & Governance","Is the solution compliant with applicable data protection and privacy regulations and internal policies?","DPIA or PIA completed and signed; GDPR Article 30 record of processing activities; data flow diagram showing where PII is stored and transmitted; DPA agreements with all sub-processors in place"),
    ("10.3","Compliance & Governance","Are audit logs enabled for critical business and security events and stored securely with defined retention?","Audit log configuration in application and infrastructure covering login, data access, and privilege changes; log retention period meeting compliance requirements (e.g., 1 year); logs stored in tamper-evident store"),
    ("10.4","Compliance & Governance","Are data classification and handling rules applied to PII and other sensitive data with appropriate controls?","Data classification policy and register; PII fields tagged in data model; data masking in non-production environments verified; data handling training completion records for all team members"),
    ("10.5","Compliance & Governance","Are data retention, archival and deletion policies defined, implemented and aligned with legal requirements?","Data retention schedule per data class aligned to legal requirements; automated archival or deletion job in /scripts/ or as a scheduled task; legal hold procedure documented"),
    ("10.6","Compliance & Governance","Are access reviews, segregation of duties and approval workflows in place for privileged operations and changes?","Quarterly access review records for privileged accounts; segregation of duties matrix; change approval workflow evidence in ITSM showing approvals required for production changes"),

    # Performance, Scalability & Resilience
    ("11.1","Performance, Scalability & Resilience","Are target NFRs for latency, throughput, concurrency and availability defined and agreed?","NFR document with quantified SLOs (e.g., P99 < 500ms, availability 99.9%, throughput 1000 RPS); stakeholder sign-off; traceability from each NFR to a corresponding architecture or design decision"),
    ("11.2","Performance, Scalability & Resilience","Have load, stress and endurance tests been executed using realistic workloads and data volumes?","Load test scripts in /tests/performance/ (k6/JMeter/Gatling); test results report showing pass or fail against NFR targets with realistic data volumes; soak test results showing stability over 24-hour period"),
    ("11.3","Performance, Scalability & Resilience","Are performance bottlenecks identified, profiled and tracked with action items?","Performance profiling results (APM traces, flame graphs) for identified bottlenecks; Jira performance improvement tickets with priority and owner; performance trend chart over last 3 sprints showing improvement"),
    ("11.4","Performance, Scalability & Resilience","Are caching, batching and asynchronous processing used where appropriate to improve performance?","Caching layer configuration (Redis/CDN/in-memory) in architecture doc and IaC; async queue or batch job implementation in codebase; cache hit rate metric visible in observability dashboard"),
    ("11.5","Performance, Scalability & Resilience","Are resiliency patterns such as timeouts, retries, circuit breakers and bulkheads implemented and tested?","Timeout, retry, and circuit breaker implementations in codebase (e.g., Resilience4j/Polly/tenacity); chaos engineering or failure injection test records; fallback behaviour documented and tested"),
    ("11.6","Performance, Scalability & Resilience","Is capacity planning done for peak load, growth and burst scenarios with monitoring to validate assumptions?","Capacity plan document with projected traffic growth and resource requirements; auto-scaling policy tested under load; capacity review records from last quarterly planning cycle with validated assumptions"),

    # APIs, Integrations & Messaging
    ("12.1","APIs, Integrations & Messaging","Are all inbound and outbound integrations clearly listed with owners, SLAs and failure modes?","Integration register or API dependency map in /docs/integrations/; each integration has named owner, SLA, and documented failure mode; no undocumented integrations visible in network traffic analysis"),
    ("12.2","APIs, Integrations & Messaging","Are API and message contracts documented and versioned (OpenAPI, AsyncAPI, schema registry)?","OpenAPI/Swagger spec in /api/openapi.yaml or /docs/api/; AsyncAPI spec for event-driven integrations; schema registry entry for Kafka/Avro topics; contract version history maintained in Git"),
    ("12.3","APIs, Integrations & Messaging","Are API gateways or integration platforms configured for authentication, routing, throttling and logging?","API gateway configuration (AWS API GW/Kong/APIM) in IaC; rate limiting and quota policies defined; authentication enforced at gateway level; access logs enabled and forwarded to logging platform"),
    ("12.4","APIs, Integrations & Messaging","Are error handling, timeouts, retries and idempotency behaviour defined and implemented for all integrations?","Integration error handling code showing timeout values, retry logic with exponential backoff, and idempotency keys; circuit breaker configuration; error handling design documented in integration spec"),
    ("12.5","APIs, Integrations & Messaging","Are contract tests or automated integration tests in place for critical APIs, queues and topics?","Contract test suite (Pact/Spring Cloud Contract) in /tests/contract/; integration test results in CI pipeline; test environment with stubbed or mocked external services for isolation and repeatability"),
    ("12.6","APIs, Integrations & Messaging","Are message schemas, routing keys, queues and topics documented and governed to avoid breaking changes?","Messaging topology diagram in /docs/messaging/; schema definitions in /schemas/ or schema registry; governance process for schema changes preventing breaking changes without version increment"),

    # User Experience & Accessibility
    ("13.1","User Experience & Accessibility","Are key user journeys and personas identified and tested end-to-end?","User journey map document with personas and flows; E2E test scenarios covering happy path and edge cases in /tests/e2e/; usability test results or UAT feedback documented per persona"),
    ("13.2","User Experience & Accessibility","Is the UI consistent with the design system or style guide for layout, typography and interactions?","Design system or style guide in Storybook/Figma/Zeroheight; UI component library in /src/components/; visual regression test results (Percy/Chromatic) showing no unintended regressions"),
    ("13.3","User Experience & Accessibility","Is the application responsive and usable across supported devices, browsers and screen sizes?","Browser compatibility matrix in test plan; cross-browser test results (BrowserStack/Sauce Labs) for supported browsers; responsive design screenshots at 320px, 768px, and 1280px breakpoints"),
    ("13.4","User Experience & Accessibility","Are accessibility guidelines (for example WCAG 2.1) considered and tested where required?","WCAG 2.1 AA audit report (axe/Lighthouse/manual); accessibility issues tracked in Jira with severity; screen reader test evidence (NVDA/JAWS/VoiceOver) for all key user flows"),
    ("13.5","User Experience & Accessibility","Is internationalisation and localisation supported where needed (text resources, date/time, currency, RTL)?","i18n framework integrated (react-i18next/ngx-translate etc.); locale resource files in /src/i18n/ or /locales/; date/time/currency formatted using locale-aware libraries; RTL layout tested if applicable"),
    ("13.6","User Experience & Accessibility","Are error states and long-running operations communicated clearly to users?","UI error state designs in Figma or Storybook; loading indicators for operations taking more than 300ms; timeout messages for operations exceeding 5s; error message usability validated in user testing"),

    # AI Adoption
    ("14.1","AI Adoption","How are AI tools currently used across development stages (coding, testing, design, documentation, DevOps)?","AI adoption log or team retrospective notes documenting tools used (GitHub Copilot, ChatGPT, Cursor etc.) and use cases per phase; enterprise or client policy document on approved AI tools"),
    ("14.2","AI Adoption","What steps are taken to verify the correctness, security, and quality of AI-generated code or artifacts?","Code review process showing AI-generated code reviewed with same rigour as hand-written code; test coverage for AI-generated modules >= 80%; static analysis applied to AI-generated code before merge"),
    ("14.3","AI Adoption","Is AI used to support architectural decisions, requirement clarification, or solution design?","Architecture Decision Records noting where AI was used in analysis; AI-assisted design artefacts reviewed and signed off by architect; any AI-generated designs validated against enterprise standards"),
    ("14.4","AI Adoption","How has AI impacted productivity, speed, or ease of development in day-to-day work?","Sprint velocity comparison before and after AI adoption; team self-assessment survey results or retrospective notes; measurable productivity metrics (PRs per sprint, story points) trending over AI adoption period"),
    ("14.5","AI Adoption","Are guidelines or restrictions for using AI tools followed (data sharing, code ownership, compliance)?","Signed AI usage policy acknowledgement for all team members; no proprietary or client data submitted to public AI tools (verified via policy and tool configuration); data classification policy applied to AI prompts"),
]

thin = Side(style="thin", color="BFBFBF")
BORDER    = Border(left=thin, right=thin, top=thin, bottom=thin)
HDR_FILL  = PatternFill("solid", fgColor="1F3864")
AREA_FILL = PatternFill("solid", fgColor="D9E1F2")
ROW1_FILL = PatternFill("solid", fgColor="EEF2FB")
ROW2_FILL = PatternFill("solid", fgColor="FFFFFF")

def hdr_font():  return Font(name="Calibri", bold=True, color="FFFFFF", size=11)
def area_font(): return Font(name="Calibri", bold=True, color="1F3864", size=10)
def body_font(): return Font(name="Calibri", size=10)
def wrap_top():  return Alignment(wrap_text=True, vertical="top")
def centered():  return Alignment(wrap_text=True, vertical="center", horizontal="center")

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Technical Check List V 1.0"

ws.column_dimensions["A"].width = 6
ws.column_dimensions["B"].width = 30
ws.column_dimensions["C"].width = 55
ws.column_dimensions["D"].width = 62
ws.column_dimensions["E"].width = 35
ws.column_dimensions["F"].width = 10

for col, h in enumerate(["#","Technical Area","Key Review Question","Expected Evidence","Reviewer Comments","RAG"], 1):
    c = ws.cell(row=1, column=col, value=h)
    c.font = hdr_font(); c.fill = HDR_FILL; c.alignment = centered(); c.border = BORDER
ws.row_dimensions[1].height = 22

for r, (sno, area, question, evidence) in enumerate(TECHNICAL_ITEMS, 2):
    fill = ROW1_FILL if r % 2 == 0 else ROW2_FILL
    for col, val in enumerate([sno, area, question, evidence, "", ""], 1):
        c = ws.cell(row=r, column=col, value=val)
        c.border = BORDER
        if col == 1:
            c.font = body_font(); c.alignment = centered(); c.fill = fill
        elif col == 2:
            c.font = area_font(); c.alignment = wrap_top(); c.fill = AREA_FILL
        else:
            c.font = body_font(); c.alignment = wrap_top(); c.fill = fill
    ws.row_dimensions[r].height = 52

ws.freeze_panes = "C2"

out = "c:/projects/nexus-ai/reviewbot/data/templates/reviewbot/v1/standard-technical.xlsx"
wb.save(out)
print(f"Saved {out}  ({len(TECHNICAL_ITEMS)} items)")
